package com.sai.enums;

public enum ConfigProperties {

    URL,
    BROWSER,
    HEADLESS,
    REMOTE,
    REMOTEURL,
    INCOGNITO,
    OVERRIDE,
    PASSEDSTEPSSCREENSHOTS,
    FAILEDSTEPSSCREENSHOTS,
    SKIPPEDSTEPSSCREENSHOTS,
    RETRYFAILEDTESTS,
    SENDRESULTSTOELK,
    ELKURL;

}
